### ISSUE TITLE
Assign and remove security groups in VM sidebar

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#595]
This issue covers the following requirements:
1. [REQ_VM_DTLS_051] A user should be able to attach security groups to VM in VM details sidebar
2. [REQ_VM_DTLS_052] A user should be able to detach security groups from VM in VM details sidebar
3. [REQ_VM_DTLS_028] A user should be able to view firewall rules in VM details sidebar

Mockup
![595](https://user-images.githubusercontent.com/26703076/35839911-92e3f9f2-0b25-11e8-8ff5-c9eb381d5eda.jpg)

**Comment by HeyRoach** [comment]
HeyRoach/595-shared-group-actions

Test to:
vm_firewall_shared_attach,
vm_firewall_shared_detach

**Comment by HeyRoach** [comment]
Todo: 

- [ ] tests

**Comment by rennervo** [comment]
Lack:1

### 1) The default group is not selected in the window attaching SG to VM

**Steps:**
1. Create 2 Shared SG
2. Create a VM and go to its sidebar on the tab "Network"
3. Click on the button to attach SG

**Actual result:** The default group is not selected, all radio buttons are in the "not selected" state
**Expected result:** By default, the first one is selected in the list.

### 2) The radio button of the first available group in the list has a gray background when you open the SG selection window

**The steps are the same as in error 1**

**Actual result:** The first radio button in the list has a gray background
**Expected result:** The radio button background is absent from the radio buttons when the window is opened, it appears only when you hover the cursor
![attach sg window](https://user-images.githubusercontent.com/26665398/52103807-24ce0f00-261a-11e9-9f6d-95d2bbb4aea1.png)

### 3) SG on detachment also detaches all groups under it in the list

**Steps:**
1. Create a VM and go to the sidebar on the tab "Network"
2. Attach to the VM one additional SG
3. Detach the top SG from the list (see screenshot)

**Actual result:** Both groups are detached from VM
**Expected result:** Only the top group is detached from VM
![detached sgs](https://user-images.githubusercontent.com/26665398/52104013-0a486580-261b-11e9-8e95-a399db1c6c8e.png)

### 4) The Private SG rule editing window is compressed when opened in the VM section

**Steps:**
1. Create a VM with Private SG
2. Go to the sidebar tab "Network"
3. Select the action "View" for Private SG
4. Click the Edit button

**Actual result:** The rule editing window is compressed in width, there is horizontal scrolling.
**Expected result:** The window does not shrink, all elements are visible in the window, no scrolling.
![psg edit rule](https://user-images.githubusercontent.com/26665398/52103727-ab362100-2619-11e9-9958-b368c12faeba.png)

**Comment by dron8552** [comment]
All issues were fixed, except the first issue, because I can't reproduce it.

**Comment by rennervo** [comment]
Lack: 2

**Error "The default group is not selected in the window attaching SG to VM" is not fixed.**

There was a problem with understanding the error. We discussed a mistake when meeting with @dron8552

**Comment by rennervo** [comment]
Tested on 1551
