### ISSUE TITLE
Buttons for change disk size are not displayed when create or resize disk - MS Edge, IE

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#940]
Browser: Edge (ver. 41.16299.15.0), IE (ver. 11.192.16299.0)

Steps:
1. Log in and go to Storage / VM sidebar.
2. Create new storage or edit old.
3. Select editable disk offering.

Actual result: Buttons of change disk size is not displayed;
Expected result: Buttons of change disk size is displayed; (Including ROOT disks)
Connected Feature ID: vm_disk_resize, storage_disk_resize, storage_disk_create

Screenshots:
![ResizeButtons.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/32a52aad-ae04-4311-bc02-a1e7b2c4fa31)

**Comment by ershovaelena** [comment]
@rennervo @chewlite @Nadya913 please note the following check-points in this issue:
1. The problem in the description is fixed
2. System checks max and min possible values and changes value entered if it is out of this range
3. If value is deleted - input becomes red which means that this field is required

It is needed to check all forms that contain this kind of inputs

**Comment by pm-Egor-Genning** [comment]
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/pm-Egor-Genning/940-input-type-number

**Comment by tamazlykar** [comment]
Update to @ershovaelena comment.
1. The original problem is not solved. IE does not know about numeric fields, so it does not show arrows. PO decided that this behavior is normal.
2. Here another problem was found, which is that these fields were not validated in the IE (see p.3).
3. After discussion with PO, it was decided to prevent user to the entry of the text values into the numeric input field and to limit the possibility of entering numbers beyond the boundaries, if this boundaries for this input field can be identified and set. 
For numeric input field with boundaries:
* input can't be empty, min value should be placed instead, exception - new untouched form (this means no error about the required field)
* input doesn't allow you enter lesser value than a minimum or greater than a maximum
4. Point 3 from @ershovaelena comment not relevant anymore

/cc @rennervo @chewlite @Nadya913

**Comment by tamazlykar** [comment]
Test on:
tamazlykar/940-input-number-validation

**Comment by chewlite** [comment]
Tested on:
tamazlykar/940-input-number-validation
